assistant:
  model:
    type: openai
    name: gpt-4-1106-preview
executor:
  model:
    type: openai
    name: gpt-4-1106-preview
user_memory_manager:
  model:
    type: openai
    name: gpt-4-1106-preview
# TODO: Fix creator based on latest improvements.
tool_creator:
  model:
    type: openai
    name: gpt-4-1106-preview